//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialStatementTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialStatementTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFXHEADER:100
        ///DATA:OFXSGML
        ///VERSION:102
        ///SECURITY:NONE
        ///ENCODING:USASCII
        ///CHARSET:1252
        ///COMPRESSION:NONE
        ///OLDFILEUID:NONE
        ///NEWFILEUID:NONE
        ///
        ///&lt;OFX&gt;
        ///&lt;SIGNONMSGSRSV1&gt;
        ///&lt;SONRS&gt;
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;DTSERVER&gt;20140318100000[-03:EST]
        ///&lt;LANGUAGE&gt;POR
        ///&lt;/SONRS&gt;
        ///&lt;/SIGNONMSGSRSV1&gt;
        ///&lt;BANKMSGSRSV1&gt;
        ///&lt;STMTTRNRS&gt;
        ///&lt;TRNUID&gt;1001
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;STMTRS&gt;
        ///&lt;CURDEF&gt;BRL
        ///&lt;BANKACCTFROM&gt;
        ///&lt;BANKID&gt;0341
        ///&lt;ACCTID&gt;7037300576
        ///&lt;ACCTTYPE&gt;CHECKING
        ///&lt;/BANKACCTFROM&gt;
        ///&lt;BANKTRANLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extrato1 {
            get {
                return ResourceManager.GetString("extrato1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFXHEADER:100
        ///DATA:OFXSGML
        ///VERSION:102
        ///SECURITY:NONE
        ///ENCODING:USASCII
        ///CHARSET:1252
        ///COMPRESSION:NONE
        ///OLDFILEUID:NONE
        ///NEWFILEUID:NONE
        ///
        ///&lt;OFX&gt;
        ///&lt;SIGNONMSGSRSV1&gt;
        ///&lt;SONRS&gt;
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;DTSERVER&gt;20140318100000[-03:EST]
        ///&lt;LANGUAGE&gt;POR
        ///&lt;/SONRS&gt;
        ///&lt;/SIGNONMSGSRSV1&gt;
        ///&lt;BANKMSGSRSV1&gt;
        ///&lt;STMTTRNRS&gt;
        ///&lt;TRNUID&gt;1001
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;STMTRS&gt;
        ///&lt;CURDEF&gt;BRL
        ///&lt;BANKACCTFROM&gt;
        ///&lt;BANKID&gt;0341
        ///&lt;ACCTID&gt;7037300576
        ///&lt;ACCTTYPE&gt;CHECKING
        ///&lt;/BANKACCTFROM&gt;
        ///&lt;BANKTRANLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extrato2 {
            get {
                return ResourceManager.GetString("extrato2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFXHEADER:100
        ///DATA:OFXSGML
        ///VERSION:102
        ///SECURITY:NONE
        ///ENCODING:USASCII
        ///CHARSET:1252
        ///COMPRESSION:NONE
        ///OLDFILEUID:NONE
        ///NEWFILEUID:NONE
        ///
        ///&lt;OFX&gt;
        ///&lt;SIGNONMSGSRSV1&gt;
        ///&lt;SONRS&gt;
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;DTSERVER&gt;20140318100000[-03:EST]
        ///&lt;LANGUAGE&gt;POR
        ///&lt;/SONRS&gt;
        ///&lt;/SIGNONMSGSRSV1&gt;
        ///&lt;BANKMSGSRSV1&gt;
        ///&lt;STMTTRNRS&gt;
        ///&lt;TRNUID&gt;1001
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;STMTRS&gt;
        ///&lt;CURDEF&gt;BRL
        ///&lt;BANKACCTFROM&gt;
        ///&lt;BANKID&gt;0341
        ///&lt;ACCTID&gt;7037300576
        ///&lt;ACCTTYPE&gt;CHECKING
        ///&lt;/BANKACCTFROM&gt;
        ///&lt;BANKTRANLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extrato3 {
            get {
                return ResourceManager.GetString("extrato3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFXHEADER:100
        ///DATA:OFXSGML
        ///VERSION:102
        ///SECURITY:NONE
        ///ENCODING:USASCII
        ///CHARSET:1252
        ///COMPRESSION:NONE
        ///OLDFILEUID:NONE
        ///NEWFILEUID:NONE
        ///
        ///&lt;OFX&gt;
        ///&lt;SIGNONMSGSRSV1&gt;
        ///&lt;SONRS&gt;
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;DTSERVER&gt;20140318100000[-03:EST]
        ///&lt;LANGUAGE&gt;POR
        ///&lt;/SONRS&gt;
        ///&lt;/SIGNONMSGSRSV1&gt;
        ///&lt;BANKMSGSRSV1&gt;
        ///&lt;STMTTRNRS&gt;
        ///&lt;TRNUID&gt;1001
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;STMTRS&gt;
        ///&lt;CURDEF&gt;BRL
        ///&lt;BANKACCTFROM&gt;
        ///&lt;BANKID&gt;0341
        ///&lt;ACCTID&gt;7037300576
        ///&lt;ACCTTYPE&gt;CHECKING
        ///&lt;/BANKACCTFROM&gt;
        ///&lt;BANKTRANLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extrato4 {
            get {
                return ResourceManager.GetString("extrato4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFXHEADER:100
        ///DATA:OFXSGML
        ///VERSION:102
        ///SECURITY:NONE
        ///ENCODING:USASCII
        ///CHARSET:1252
        ///COMPRESSION:NONE
        ///OLDFILEUID:NONE
        ///NEWFILEUID:NONE
        ///
        ///&lt;OFX&gt;
        ///&lt;SIGNONMSGSRSV1&gt;
        ///&lt;SONRS&gt;
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;DTSERVER&gt;20140318100000[-03:EST]
        ///&lt;LANGUAGE&gt;POR
        ///&lt;/SONRS&gt;
        ///&lt;/SIGNONMSGSRSV1&gt;
        ///&lt;BANKMSGSRSV1&gt;
        ///&lt;STMTTRNRS&gt;
        ///&lt;TRNUID&gt;1001
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;STMTRS&gt;
        ///&lt;CURDEF&gt;BRL
        ///&lt;BANKACCTFROM&gt;
        ///&lt;BANKID&gt;0341
        ///&lt;ACCTID&gt;7037300576
        ///&lt;ACCTTYPE&gt;CHECKING
        ///&lt;/BANKACCTFROM&gt;
        ///&lt;BANKTRANLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extrato5 {
            get {
                return ResourceManager.GetString("extrato5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFXHEADER:100
        ///DATA:OFXSGML
        ///VERSION:102
        ///SECURITY:NONE
        ///ENCODING:USASCII
        ///CHARSET:1252
        ///COMPRESSION:NONE
        ///OLDFILEUID:NONE
        ///NEWFILEUID:NONE
        ///
        ///&lt;OFX&gt;
        ///&lt;SIGNONMSGSRSV1&gt;
        ///&lt;SONRS&gt;
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;DTSERVER&gt;20140318100000[-03:EST]
        ///&lt;LANGUAGE&gt;POR
        ///&lt;/SONRS&gt;
        ///&lt;/SIGNONMSGSRSV1&gt;
        ///&lt;BANKMSGSRSV1&gt;
        ///&lt;STMTTRNRS&gt;
        ///&lt;TRNUID&gt;1001
        ///&lt;STATUS&gt;
        ///&lt;CODE&gt;0
        ///&lt;SEVERITY&gt;INFO
        ///&lt;/STATUS&gt;
        ///&lt;STMTRS&gt;
        ///&lt;CURDEF&gt;BRL
        ///&lt;BANKACCTFROM&gt;
        ///&lt;BANKID&gt;0341
        ///&lt;ACCTID&gt;7037300576
        ///&lt;ACCTTYPE&gt;CHECKING
        ///&lt;/BANKACCTFROM&gt;
        ///&lt;BANKTRANLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extrato6 {
            get {
                return ResourceManager.GetString("extrato6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string extrato7 {
            get {
                return ResourceManager.GetString("extrato7", resourceCulture);
            }
        }
    }
}
